apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: vote
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: vote
  type: LoadBalancer
status:
  loadBalancer: {}
